sudo: required
language: csharp
mono: none
dotnet: 2.1

branches:
  except:
    # this is required to avoid building tags.
    - /^v?\d+\.\d+\.\d+(\w*\W*)*$/
script: 
  - sed -i -e "s/000/${TRAVIS_BUILD_NUMBER^^}/g" $TRAVIS_BUILD_DIR/templates/templates.csproj
  - dotnet build $TRAVIS_BUILD_DIR/templates/templates.csproj -c release -o $TRAVIS_BUILD_DIR/build/templates
  # need to test the solution AFTER the package is built 
  - dotnet test $TRAVIS_BUILD_DIR/templates/api-template/test
deploy:
  - provider: script
    skip_cleanup: true
    script: dotnet nuget push $TRAVIS_BUILD_DIR/build/templates/NachoColl.Cloudformation4dotNET.Templates.*.nupkg --api-key $NUGET_APIKEY --source https://www.nuget.org 
    on: master 
