sudo: required
language: csharp
mono: none
dotnet: 2.1
    
branches:
  except:
    # this is required to avoid building tags.
    - /^v?\d+\.\d+\.\d+(\w*\W*)*$/
    # dev brach should not be published.
    - dev
install:
  # install awscli for deploying
  - pip install awscli --upgrade --user
  # install Cloudformation4dotNET tool
  - dotnet tool install NachoColl.Cloudformation4dotNET --version 0.0.* --tool-path $TRAVIS_BUILD_DIR/tools
script:
  # unit testing
  - dotnet test $TRAVIS_BUILD_DIR/test
deploy:
  - provider: script
    skip_cleanup: true
    script: bash $TRAVIS_BUILD_DIR/.deploy.sh test
    on: test
  - provider: script
    skip_cleanup: true
    script: bash $TRAVIS_BUILD_DIR/.deploy.sh staging 
    on: staging
  - provider: script
    skip_cleanup: true
    script: bash $TRAVIS_BUILD_DIR/.deploy.sh prod 
    on: master
